before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: typ0
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: typ0
    homepage: "https://github.com/TusharIbtekar/go-typ0"
    description: "A CLI typing practice tool"
    repository:
      owner: TusharIbtekar
      name: homebrew-go-typ0
    commit_author:
      name: github-actions[bot]
      email: github-actions[bot]@users.noreply.github.com
    folder: Formula
    homepage_install: |
      brew install TusharIbtekar/go-typ0/typ0

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch
